apiVersion: 1

datasources:
- name: ClickHouse
  type: grafana-clickhouse-datasource
  jsonData:
    port: 9000
    server: clickhouse
    username: default
    tlsSkipVerify: true
    logs:
      defaultDatabase: default
      defaultTable: logs
      timeColumn: time
      levelColumn: level
      messageColumn: message
      column: playerName
  isDefault: true